<a href="https://colab.research.google.com/github/saivenkat-p/PW-SKILLS/blob/main/SQL_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SQL Basics - Employees Data

In [87]:
import sqlite3
import pandas as pd

# Create/connect to SQLite database
conn = sqlite3.connect("company_db.db")

print("Database connected successfully!")

Database connected successfully!

### Q1 — Create employees table

In [88]:
conn.execute("""
CREATE TABLE IF NOT EXISTS employees (
    employee_id INTEGER PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    department VARCHAR(50),
    salary INTEGER,
    hire_date DATE
)
""")

conn.commit()

print("Employees table created successfully!")

Employees table created successfully!

### Q2 — Insert employee data

In [89]:
conn.execute("""
DELETE FROM employees
""")

conn.executemany("""
INSERT INTO employees
(employee_id, first_name, last_name, department, salary, hire_date)
VALUES (?, ?, ?, ?, ?, ?)
""", [
    (101, 'Amit', 'Sharma', 'HR', 50000, '2020-01-15'),
    (102, 'Riya', 'Kapoor', 'Sales', 75000, '2019-03-22'),
    (103, 'Raj', 'Mehta', 'IT', 90000, '2018-07-11'),
    (104, 'Neha', 'Verma', 'IT', 85000, '2021-09-01'),
    (105, 'Arjun', 'Singh', 'Finance', 60000, '2022-02-10')
])

conn.commit()

print("Employee data inserted successfully!")

Employee data inserted successfully!

In [90]:
pd.read_sql_query("""
SELECT *
FROM employees
""", conn)

   employee_id first_name last_name department  salary   hire_date
0          101       Amit    Sharma         HR   50000  2020-01-15
1          102       Riya    Kapoor      Sales   75000  2019-03-22
2          103        Raj     Mehta         IT   90000  2018-07-11
3          104       Neha     Verma         IT   85000  2021-09-01
4          105      Arjun     Singh    Finance   60000  2022-02-10

### Q3 — Salary: Lowest to Highest

In [91]:
employees_by_salary = pd.read_sql_query("""
SELECT *
FROM employees
ORDER BY salary ASC
""", conn)

employees_by_salary

   employee_id first_name last_name department  salary   hire_date
0          101       Amit    Sharma         HR   50000  2020-01-15
1          105      Arjun     Singh    Finance   60000  2022-02-10
2          102       Riya    Kapoor      Sales   75000  2019-03-22
3          104       Neha     Verma         IT   85000  2021-09-01
4          103        Raj     Mehta         IT   90000  2018-07-11

### Q4 — Department A–Z and Salary High–Low

In [92]:
employees_by_department_salary = pd.read_sql_query("""
SELECT *
FROM employees
ORDER BY department ASC, salary DESC
""", conn)

employees_by_department_salary

   employee_id first_name last_name department  salary   hire_date
0          105      Arjun     Singh    Finance   60000  2022-02-10
1          101       Amit    Sharma         HR   50000  2020-01-15
2          103        Raj     Mehta         IT   90000  2018-07-11
3          104       Neha     Verma         IT   85000  2021-09-01
4          102       Riya    Kapoor      Sales   75000  2019-03-22

### Q5 — IT employees, newest hire first

In [93]:
it_employees = pd.read_sql_query("""
SELECT *
FROM employees
WHERE department = 'IT'
ORDER BY hire_date DESC
""", conn)

it_employees

   employee_id first_name last_name department  salary   hire_date
0          104       Neha     Verma         IT   85000  2021-09-01
1          103        Raj     Mehta         IT   90000  2018-07-11

#Q6 - Create Sales table

In [96]:


conn.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY,
    customer_name VARCHAR(50),
    amount INTEGER,
    sale_date DATE
)
""")

conn.execute("DELETE FROM sales")

conn.executemany("""
INSERT INTO sales (sale_id, customer_name, amount, sale_date)
VALUES (?, ?, ?, ?)
""", [
    (1, 'Aditi', 1500, '2024-08-01'),
    (2, 'Rohan', 2200, '2024-08-03'),
    (3, 'Aditi', 3500, '2024-09-05'),
    (4, 'Meena', 2700, '2024-09-15'),
    (5, 'Rohan', 4500, '2024-09-25')
])

conn.commit()

print("Sales table created and data inserted successfully.")

Sales table created and data inserted successfully.

##Q7

In [97]:
sales_by_amount = pd.read_sql_query("""
SELECT *
FROM sales
ORDER BY amount DESC
""", conn)

sales_by_amount

   sale_id customer_name  amount   sale_date
0        5         Rohan    4500  2024-09-25
1        3         Aditi    3500  2024-09-05
2        4         Meena    2700  2024-09-15
3        2         Rohan    2200  2024-08-03
4        1         Aditi    1500  2024-08-01

##Q8

In [98]:
aditi_sales = pd.read_sql_query("""
SELECT *
FROM sales
WHERE customer_name = 'Aditi'
""", conn)

aditi_sales

   sale_id customer_name  amount   sale_date
0        1         Aditi    1500  2024-08-01
1        3         Aditi    3500  2024-09-05

### Q9. What is the Difference Between a Primary Key and a Foreign Key?

**Primary Key:** A column that uniquely identifies each record in a table. It cannot contain duplicate or NULL values.

**Foreign Key:** A column that references the Primary Key of another table and is used to establish a relationship between two tables.

---

### Q10. What Are Constraints in SQL and Why Are They Used?

**Constraints** are rules applied to columns in a table to maintain **data accuracy, consistency, and integrity**.

Common constraints include:

* **PRIMARY KEY** – uniquely identifies each record.
* **FOREIGN KEY** – establishes a relationship between tables.
* **NOT NULL** – prevents NULL values.
* **UNIQUE** – prevents duplicate values.
* **CHECK** – ensures values meet a specified condition.
* **DEFAULT** – provides a default value when no value is supplied.